<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Music.Library.Repository\Music.Library.Repository.csproj" />
      <ProjectReference Include="..\Music.Library.Shared\Music.Library.Shared.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Music.Catalogue.ClientHttp" Version="2.0.0" />
      <PackageReference Include="Music.Catalogue.Shared" Version="1.0.6" />
      <PackageReference Include="Utility.Kafka.2025" Version="2.0.1" />
    </ItemGroup>

</Project>
